import { library, config } from '@fortawesome/fontawesome-svg-core'
import {
  faBars,
  faTimes,
  faSearch,
  faHome,
  faSignInAlt,
  faSignOutAlt,
  faAngleRight,
  faAngleLeft,
  faUser,
  faUsers,
  faPlay,
  faPause,
  faSyncAlt,
  faVolumeUp,
  faVolumeMute,
  faVolumeDown,
  faPlus,
  faAngleUp,
  faAngleDown,
  faRandom,
  faStepForward,
  faStepBackward,
  faRetweet,
} from '@fortawesome/free-solid-svg-icons'

config.autoAddCss = false

library.add(
  faBars,
  faTimes,
  faSearch,
  faHome,
  faSignInAlt,
  faSignOutAlt,
  faAngleRight,
  faAngleLeft,
  faUser,
  faUsers,
  faPlay,
  faPause,
  faSyncAlt,
  faVolumeUp,
  faVolumeMute,
  faVolumeDown,
  faPlus,
  faAngleUp,
  faAngleDown,
  faRandom,
  faStepForward,
  faStepBackward,
  faRetweet,
)
